[package]
name = "moulinette_cli"
version = "0.1.0"
authors = ["okno <paul.delafosse@protonmail.com>"]
edition = "2018"


[dependencies]
moulinette = { path = "../moulinette_lib"}

clap = "2.33.0"
shiplift = "0.5"
tokio = "0.1.22"

env_logger = "0.6"
